# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.IntegerField()),
                ('description', models.TextField()),
                ('put_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
