# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_flag', models.BooleanField()),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabby.Reply')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabby.Tuser')),
            ],
        ),
    ]
