# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabby', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
