# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabby', '0004_tuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='put_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='put_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
