# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabby', '0005_auto_20171221_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='username',
        ),
    ]
