# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabby', '0007_auto_20171222_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
