# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabby', '0010_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
